In [ ]:
import numpy as np 

In [ ]:
input_values = np.array([[0,0],[0,1],[1,0],[1,1]])
input_values

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
input_values.shape

(4, 2)

In [ ]:
output = np.array([0,1,1,0])
output

array([0, 1, 1, 0])

In [ ]:
output.shape

(4,)

In [ ]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [ ]:
bias  = 0.3

In [ ]:
def sigmoid_func(x):
  return 1/(1 + np.exp(-x))

In [ ]:
def der(x):
  return sigmoid_func(x) * (1 - sigmoid_func(x))

In [ ]:
for epochs in range(1000):
  input_arr = input_values
  weighted_sum = np.dot(input_arr , weights) + bias
  first_output = sigmoid_func(weighted_sum)

  error = first_output - output
  total_error = np.square(np.subtract(first_output , output)).mean()

  first_der = error
  second_der = der(first_output)
  derivative = first_der * second_der

  t_input = input_values.T
  final_derivative = np.dot(t_input , derivative)

  weights = weights - 0.05 * final_derivative

  for i in derivative:
    bias = bias - 0.04 * i

print("Weights", weights)
print("Bias", bias)

Weights [[-1.30458287  1.16717147  1.16717147 -1.30458287]
 [-1.25430382  1.2213744   1.2213744  -1.25430382]]
Bias [-2.87514222  2.76365938  2.76365938 -2.87514222]


In [ ]:

pred = np.array([0,1])

result = np.dot(pred, weights) + bias

res = sigmoid_func(result)

print(res)

[0.01583695 0.98174753 0.98174753 0.01583695]
