In [1]:
import tensorflow as tf
import numpy as np 

print(tf.__version__)

2.3.0


**Tensors Constant**

In [2]:
x = tf.constant([[1,2,3],
                 [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

**Slicing**

In [4]:
y = x[:,:2]
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

**Reshaping**

In [6]:
y = tf.reshape(x,[3,2])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

**Rank 0 Tensor or a Scalar tensor**

In [7]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
print(rank_0_tensor.shape)


tf.Tensor(4, shape=(), dtype=int32)
()


**Vector or Rank 1 Tensor**

In [8]:
rank_1_tensor = tf.constant([2. , 4 , 6])
print(rank_1_tensor)
print(rank_1_tensor.shape)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)
(3,)


**Matrix or Rank 2 Tensor**

In [9]:
rank_2_tensor = tf.constant([[1,2,4],
                             [4,5,6]])
print(rank_2_tensor)
print(rank_2_tensor.shape)

tf.Tensor(
[[1 2 4]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)


**Tensors have many Axes here is Rank 3 Tensor**



In [13]:
rank_3_tensor = tf.constant([[[1,2,3],
                             [4,5,6]],
                           [[7,8,9],
                            [10,11,12]],
                           [[13,14,15],
                            [16,17,18]]])
print(rank_3_tensor)
print(rank_3_tensor.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
(3, 2, 3)


**How to Convert a Tensor into Numpy Array**

In [14]:
np.array(rank_2_tensor)

array([[1, 2, 4],
       [4, 5, 6]], dtype=int32)

**An other method**

In [15]:
rank_2_tensor.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [4, 5, 6]], dtype=int32)>>

**Basic Math on Tensors**

In [18]:
a = tf.constant([[1,2],
                 [4,5]])
b = tf.constant([[2,2],
                 [4,4]])

print(tf.add(a , b) , "\n")
print(tf.multiply(a , b), "\n")
print(tf.matmul(a , b), "\n")

tf.Tensor(
[[3 4]
 [8 9]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 2  4]
 [16 20]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[10 10]
 [28 28]], shape=(2, 2), dtype=int32) 



In [20]:
a = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
b = tf.constant([[2,2,2],
                 [4,4,4],
                 [6,6,6]])

print(tf.add(a , b) , "\n")
print(tf.multiply(a , b), "\n")
print(tf.matmul(a , b), "\n")

tf.Tensor(
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[ 2  4  6]
 [16 20 24]
 [42 48 54]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[ 28  28  28]
 [ 64  64  64]
 [100 100 100]], shape=(3, 3), dtype=int32) 



**Also we can do Arithematic Operations using these**

In [21]:
print(a + b,"\n")
print(a * b, "\n")
print(a @ b, "\n")

tf.Tensor(
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[ 2  4  6]
 [16 20 24]
 [42 48 54]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[ 28  28  28]
 [ 64  64  64]
 [100 100 100]], shape=(3, 3), dtype=int32) 



**Some other Math Operations**

In [25]:
x = tf.constant([[4. , 6.],[10. , 6.]])

# Find maximum number in the tensor 
print(tf.reduce_max(x))
# Find the Index of the maximum number in the tensor
print(tf.math.argmax(x))

# Compute the Softmax 
tf.nn.softmax(x)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.11920291, 0.880797  ],
       [0.98201376, 0.01798621]], dtype=float32)>

**Shapes of a Tensor**

Tensors have shapes. Some vocabulary:

 * Shape: The length (number of elements) of each of the dimensions of a tensor.
 * Rank: Number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
 * Axis or Dimension: A particular dimension of a tensor.
 * Size: The total number of items in the tensor, the product shape vector

 
Note: Although you may see reference to a "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

Tensors and tf.TensorShape objects have convenient properties for accessing these:

In [26]:
rank_4_tensor = tf.zeros([3,2,4,5])

In [27]:
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
print("Type of every Element:", rank_4_tensor.dtype)
print("Number of Dimensions:",rank_4_tensor.ndim)
print("Shape of Tensor:",rank_4_tensor.shape)
print("Elements Along axis 0 of Tensor:",rank_4_tensor.shape[0])
print("Elements Along last axis of Tensor:",rank_4_tensor.shape[-1])
print("Total number of Elements:",tf.size(rank_4_tensor).numpy())

Type of every Element: <dtype: 'float32'>
Number of Dimensions: 4
Shape of Tensor: (3, 2, 4, 5)
Elements Along axis 0 of Tensor: 3
Elements Along last axis of Tensor: 5
Total number of Elements: 120


**Indexing**

In [30]:
rank_1_tensor = tf.constant([0 , 1 ,2 , 3 , 4 , 5 , 6 ,7 , 8 , 9 , 10])
print(rank_1_tensor.numpy())

[ 0  1  2  3  4  5  6  7  8  9 10]


In [35]:
print("First:",rank_1_tensor[0].numpy())
print("Second:",rank_1_tensor[1].numpy())
print("Last:",rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 10


**Slicing**

In [38]:
print("Everything:",rank_1_tensor[:])
print("Before 4:",rank_1_tensor[:5])
print("From 4 to the End:",rank_1_tensor[5:])
print("From 2 and before 7:",rank_1_tensor[2:7])
print("Every Other Item:",rank_1_tensor[::2])
print("Reversed:", rank_1_tensor[::-1])

Everything: tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10], shape=(11,), dtype=int32)
Before 4: tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
From 4 to the End: tf.Tensor([ 5  6  7  8  9 10], shape=(6,), dtype=int32)
From 2 and before 7: tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
Every Other Item: tf.Tensor([ 0  2  4  6  8 10], shape=(6,), dtype=int32)
Reversed: tf.Tensor([10  9  8  7  6  5  4  3  2  1  0], shape=(11,), dtype=int32)


** *italicized text*Multi Axis Indexing**

In [40]:
print(rank_2_tensor.numpy())

[[1 2 4]
 [4 5 6]]


In [41]:
print(rank_2_tensor[1 , 1].numpy())

5


**You can index using any combination integers and slices:**

In [45]:
print("Second Row:",rank_2_tensor[1 ,:].numpy())
print("Second Column:",rank_2_tensor[ : , 1:2].numpy())
print("Last Row:",rank_2_tensor[-1, ].numpy())
print("First item in Last Row:",rank_2_tensor[-1,0].numpy())
print("Skip the First Row:",rank_2_tensor[1:, :].numpy())

Second Row: [4 5 6]
Second Column: [[2]
 [5]]
Last Row: [4 5 6]
First item in Last Row: 4
Skip the First Row: [[4 5 6]]


**Example of a rank_3_tensor**

In [46]:
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [47]:
print(rank_3_tensor[: , : , 1:2])

tf.Tensor(
[[[ 2]
  [ 5]]

 [[ 8]
  [11]]

 [[14]
  [17]]], shape=(3, 2, 1), dtype=int32)


**Manipulation Shape**

In [54]:
var_x = tf.Variable(tf.constant([[1],[2],[3]]))
print(var_x.shape)

(3, 1)


In [56]:
# Converting this obect to a python List 
print(var_x.shape.as_list())

[3, 1]


**You can reshape a tensor into a new shape. Reshaping is fast and cheap as the underlying data does not need to be duplicated.**

In [57]:
reshaped = tf.reshape(var_x , [1,3])

In [58]:
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [59]:
print(var_x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [60]:
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [61]:
print(tf.reshape(rank_3_tensor , [-1]))

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18], shape=(18,), dtype=int32)


In [64]:
print(tf.reshape(rank_3_tensor, [3*2, 3]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]], shape=(6, 3), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]], shape=(3, 6), dtype=int32)


**BroadCasting**

Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [65]:
x = tf.constant([1 , 2 ,3])
y = tf.constant(2)
z = tf.constant([2,2,2])

print(tf.multiply(x ,2))
print(x *y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Likewise, 1-sized dimensions can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.

In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to produce a 3x4 matrix. Note how the leading 1 is optional: The shape of y is [4].

In [68]:
x = tf.reshape(x , [3,1])
y = tf.range(1 , 5)

print(x,"\n")
print(y,"\n")
print(tf.multiply(x , y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Here is the same operation without broadcasting:

In [69]:
x_stretch = tf.constant([[1,1,1,1],
                         [2,2,2,2],
                         [3,3,3,3]])
y_stretch = tf.constant([[1,2,3,4],
                         [1,2,3,4],
                         [1,2,3,4]])

print(x_stretch * y_stretch)

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Most of the time, broadcasting is both time and space efficient, as the broadcast operation never materializes the expanded tensors in memory.

You see what broadcasting looks like using tf.broadcast_to.

In [70]:
print(tf.broadcast_to(tf.constant([1. , 2. , 3.]) , [3,3]))

tf.Tensor(
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]], shape=(3, 3), dtype=float32)



Unlike a mathematical op, for example, broadcast_to does nothing special to save memory. Here, you are materializing the tensor.