## Tensorflow Dataset API

**Learning Objectives**

- Learn how to use tf.data to read data from memory
- Learn how to use tf.data in a training loop
- Learn how to use tf.data to read data from disk
- Learn how to write production input pipelines with feature engineering (batching, shuffling, etc.)


In this notebook, we will start by refactoring the linear regression we implemented in the previous lab so that it takes data from a tf.data.Dataset, and we will learn how to implement **stochastic gradient descent** with it. In this case, the original dataset will be synthetic and read by the tf.data API directly from memory.

In a second part, we will learn how to load a dataset with the tf.data API when the dataset resides on *disk*

In [1]:
# The json modeule is used to convert python dictionary into a json file that is written in the file
import json
import math # for arithmetic operations
import os # for interacting with Operating System
from pprint import pprint # The pprint module provides a capability to `pretty-print` arbitrary Python data structures in a form which can be used as input to the interpreter

import numpy as np 
import tensorflow as tf 

## Loading data from Memory 

### Creating the dataset

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
X = tf.constant(range(10), dtype=tf.float32)
Y = 2 * X + 10


We begin with implementing a function that takes as input

- our $X$ and $Y$ vectors of synthetic data generated by the linear function $y= 2x + 10$

- the number of passes over the dataset we want to train on (epochs)

- the size of the batches the dataset (batch_size)

- and returns a tf.data.Dataset:

**Remark:** Note that the last batch may not contain the exact number of elements you specified because the dataset was exhausted.

If you want batches with the exact same number of elements per batch, we will have to discard the last batch by setting:

dataset = dataset.batch(batch_size, drop_remainder=True)
We will do that here.

In [4]:
def create_dataset(X,Y,epochs,batch_size):
  # Using the tf.data.Dataset.from_tensor_slices() method we are able to get the slices of list or array
  dataset = tf.data.Dataset.from_tensor_slices((X,Y))
  dataset = dataset.repeat(epochs).batch(batch_size,drop_remainder=True)
  return dataset

Let's test our function by iterating twice over our dataset in batches of 3 datapoints

In [5]:
BATCH_SIZE = 3
EPOCHS = 2

dataset = create_dataset(X,Y,epochs=1, batch_size=3)

for i, (x,y) in enumerate(dataset):
  print("X:",x.numpy(),"y:",y.numpy())

  assert len(x) == BATCH_SIZE
  assert len(y) == BATCH_SIZE

assert EPOCHS

X: [0. 1. 2.] y: [10. 12. 14.]
X: [3. 4. 5.] y: [16. 18. 20.]
X: [6. 7. 8.] y: [22. 24. 26.]


## Loss Function and Gradient

In [6]:
# Let's define loss_mse() procedure which will return computed mean of elements across dimensions of a tensor.
def loss_mse(X, Y, w0, w1):
    Y_hat = w0 * X + w1
    errors = (Y_hat - Y)**2
    return tf.reduce_mean(errors)

# Let's define compute_gradients() procedure which will return value of recorded operations for automatic differentiation
def compute_gradients(X, Y, w0, w1):
    with tf.GradientTape() as tape:
        loss = loss_mse(X, Y, w0, w1)
    return tape.gradient(loss, [w0, w1])

**Training Loop**

In [7]:
EPOCHS = 250
BATCH_SIZE = 2
LEARNING_RATE = 0.02

MSG = "STEP {step} - loss: {loss}, w0: {w0}, w1: {w1}\n"

w0 = tf.Variable(0.0)
w1 = tf.Variable(0.0)

dataset = create_dataset(X,Y,epochs=EPOCHS,batch_size=BATCH_SIZE)

for step,(X_batch , Y_batch) in enumerate(dataset):
  dw0,dw1 = compute_gradients(X_batch , Y_batch , w0 , w1)
  w0.assign_sub(dw0 * LEARNING_RATE)
  w1.assign_sub(dw1 * LEARNING_RATE)

  if step % 100 == 0:
    loss = loss_mse(X_batch , Y_batch , w0 , w1)
    print(MSG.format(step = step , loss = loss , w0 = w0.numpy() , w1 = w1.numpy()))

assert loss < 0.0001
assert (w0 - 2) < 0.001
assert (w1 - 10) < 0.001

STEP 0 - loss: 109.76800537109375, w0: 0.23999999463558197, w1: 0.4399999976158142

STEP 100 - loss: 9.363959312438965, w0: 2.55655837059021, w1: 6.674341678619385

STEP 200 - loss: 1.393267273902893, w0: 2.2146825790405273, w1: 8.717182159423828

STEP 300 - loss: 0.20730558037757874, w0: 2.082810878753662, w1: 9.505172729492188

STEP 400 - loss: 0.03084510937333107, w0: 2.03194260597229, w1: 9.809128761291504

STEP 500 - loss: 0.004589457996189594, w0: 2.012321710586548, w1: 9.926374435424805

STEP 600 - loss: 0.0006827632314525545, w0: 2.0047526359558105, w1: 9.971602439880371

STEP 700 - loss: 0.00010164897685172036, w0: 2.0018346309661865, w1: 9.989042282104492

STEP 800 - loss: 1.5142451957217418e-05, w0: 2.000706911087036, w1: 9.995771408081055

STEP 900 - loss: 2.256260358990403e-06, w0: 2.0002737045288086, w1: 9.998367309570312

STEP 1000 - loss: 3.3405058275093324e-07, w0: 2.000105381011963, w1: 9.999371528625488

STEP 1100 - loss: 4.977664502803236e-08, w0: 2.000040054321289,

## Loading Data from Disk

**Use tf.data to read the CSV files**


The tf.data API can easily read csv files using the helper function tf.data.experimental.make_csv_dataset

If you have TFRecords (which is recommended), you may use tf.data.experimental.make_batched_features_dataset

The first step is to define

- the feature names into a list CSV_COLUMNS
- their default values into a list DEFAULTS

In [8]:
CSV_COLUMNS = [
    'fare_amount',
    'pickup_datetime',
    'pickup_longitude',
    'pickup_latitude',
    'dropoff_longitude',
    'dropoff_latitude',
    'passenger_count',
    'key'
]

LABEL_COLUMN = "fare_amount"

DEFAULTS = [[0.0], ['na'], [0.0], [0.0], [0.0], [0.0], [0.0], ['na']]

In [9]:
def create_dataset(pattern):
  return tf.data.experimental.make_csv_dataset(pattern , 1 , CSV_COLUMNS , DEFAULTS)

tempds = create_dataset("/content/drive/MyDrive/Datasets/Taxi/taxi-train.csv")
print(tempds)

<PrefetchDataset shapes: OrderedDict([(fare_amount, (1,)), (pickup_datetime, (1,)), (pickup_longitude, (1,)), (pickup_latitude, (1,)), (dropoff_longitude, (1,)), (dropoff_latitude, (1,)), (passenger_count, (1,)), (key, (1,))]), types: OrderedDict([(fare_amount, tf.float32), (pickup_datetime, tf.string), (pickup_longitude, tf.float32), (pickup_latitude, tf.float32), (dropoff_longitude, tf.float32), (dropoff_latitude, tf.float32), (passenger_count, tf.float32), (key, tf.string)])>


Note that this is a prefetched dataset, where each element is an OrderedDict whose keys are the feature names and whose values are tensors of shape (1,) (i.e. vectors).

In [10]:
# Let's iterate over the first two element of this dataset using `dataset.take(2)`.
# Then convert them ordinary Python dictionary with numpy array as values for more readability:

for data in tempds.take(2):
  pprint({k: v.numpy() for k , v in data.items()})
  print("\n")

{'dropoff_latitude': array([40.730534], dtype=float32),
 'dropoff_longitude': array([-73.98619], dtype=float32),
 'fare_amount': array([8.5], dtype=float32),
 'key': array([b'2640'], dtype=object),
 'passenger_count': array([1.], dtype=float32),
 'pickup_datetime': array([b'2014-12-22 19:41:41 UTC'], dtype=object),
 'pickup_latitude': array([40.755985], dtype=float32),
 'pickup_longitude': array([-73.97253], dtype=float32)}


{'dropoff_latitude': array([40.677856], dtype=float32),
 'dropoff_longitude': array([-73.98826], dtype=float32),
 'fare_amount': array([5.5], dtype=float32),
 'key': array([b'6448'], dtype=object),
 'passenger_count': array([1.], dtype=float32),
 'pickup_datetime': array([b'2014-02-24 18:22:00 UTC'], dtype=object),
 'pickup_latitude': array([40.677395], dtype=float32),
 'pickup_longitude': array([-73.97987], dtype=float32)}




## Transforming the Features


What we really need is a dictionary of features + a label. So, we have to do two things to the above dictionary:

- Remove the unwanted column "key"
- Keep the label separate from the features

Let's first implement a function that takes as input a row (represented as an OrderedDict in our tf.data.Dataset as above) and then returns a tuple with two elements:

- The first element being the same OrderedDict with the label dropped
- The second element being the label itself (fare_amount)
Note that we will need to also remove the key and pickup_datetime column, which we won't use.

In [11]:
UNWANTED_COLS = ["pickup_datetime", "key"]

def features_and_labels(row_data):
  labels = row_data.pop(LABEL_COLUMN)
  features = row_data

  for unwanter_cols in UNWANTED_COLS:
    features.pop(unwanter_cols)

  return features,labels

In [12]:
for row_data in tempds.take(2):
  features,labels = features_and_labels(row_data)
  pprint(features)
  print(labels, "\n")

  assert UNWANTED_COLS[0] not in features.keys()
  assert UNWANTED_COLS[1] not in features.keys()
  assert labels.shape == 1

OrderedDict([('pickup_longitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-73.972305], dtype=float32)>),
             ('pickup_latitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([40.76222], dtype=float32)>),
             ('dropoff_longitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-73.98782], dtype=float32)>),
             ('dropoff_latitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([40.76145], dtype=float32)>),
             ('passenger_count',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)])
tf.Tensor([8.], shape=(1,), dtype=float32) 

OrderedDict([('pickup_longitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-73.978676], dtype=float32)>),
             ('pickup_latitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([40.76279], dtype=float32)>),
             ('dropoff_longitude',
              <tf.T

## Batching


Let's now refactor our create_dataset function so that it takes an additional argument batch_size and batch the data correspondingly. We will also use the features_and_labels function we implemented for our dataset to produce tuples of features and labels.



In [13]:
def create_dataset(pattern, batch_size):
  dataset =  tf.data.experimental.make_csv_dataset(pattern , batch_size , CSV_COLUMNS , DEFAULTS)

  return dataset.map(features_and_labels)

In [14]:
BATCH_SIZE = 2
tempds = tempds = create_dataset("/content/drive/MyDrive/Datasets/Taxi/taxi-train.csv" , batch_size= 2)

for X_batch , Y_batch in tempds.take(2):
  pprint({k: v.numpy() for k , v in X_batch.items()})
  print(Y_batch.numpy(),"\n")

  assert len(Y_batch) == BATCH_SIZE

{'dropoff_latitude': array([40.76303, 40.70576], dtype=float32),
 'dropoff_longitude': array([-73.96674 , -74.009964], dtype=float32),
 'passenger_count': array([5., 2.], dtype=float32),
 'pickup_latitude': array([40.719963, 40.738842], dtype=float32),
 'pickup_longitude': array([-74.00014, -73.98321], dtype=float32)}
[17.  13.3] 

{'dropoff_latitude': array([40.75059, 40.75461], dtype=float32),
 'dropoff_longitude': array([-73.98078, -73.9798 ], dtype=float32),
 'passenger_count': array([5., 1.], dtype=float32),
 'pickup_latitude': array([40.740936, 40.761875], dtype=float32),
 'pickup_longitude': array([-73.98156, -73.97502], dtype=float32)}
[7. 4.] 



## Shuffling

When training a deep learning model in batches over multiple workers, it is helpful if we shuffle the data. That way, different workers will be working on different parts of the input file at the same time, and so averaging gradients across workers will help. Also, during training, we will need to read the data indefinitely.

Let's refactor our create_dataset function so that it shuffles the data, when the dataset is used for training.

We will introduce an additional argument mode to our function to allow the function body to distinguish the case when it needs to shuffle the data (mode == "train") from when it shouldn't (mode == "eval").

Also, before returning we will want to prefetch 1 data point ahead of time (dataset.prefetch(1)) to speed-up training:

In [15]:
def create_dataset(pattern, batch_size = 1, mode= "eval"):
  dataset =  tf.data.experimental.make_csv_dataset(pattern , batch_size , CSV_COLUMNS , DEFAULTS)

  dataset.map(features_and_labels)

  if mode == "train":
    dataset = dataset.shuffle(1000).repeat()

    dataset = dataset.prefetch(1)

    return dataset

In [23]:
tempds = create_dataset("/content/drive/MyDrive/Datasets/Taxi/taxi-train.csv" , 2, "train")
print(list(tempds.take(1)))

[OrderedDict([('fare_amount', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([7.5, 9.3], dtype=float32)>), ('pickup_datetime', <tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'2014-12-08 21:50:00 UTC', b'2012-02-21 11:53:00 UTC'],
      dtype=object)>), ('pickup_longitude', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-73.97611, -73.98924], dtype=float32)>), ('pickup_latitude', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([40.76469 , 40.739544], dtype=float32)>), ('dropoff_longitude', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-73.9792, -73.9966], dtype=float32)>), ('dropoff_latitude', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([40.75333, 40.72363], dtype=float32)>), ('passenger_count', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([6., 1.], dtype=float32)>), ('key', <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'881', b'3511'], dtype=object)>)])]
